# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
    -run:
      name: lighthouse audits to seriesci
      command: |
      npm run build
      cd build
      python3 -m http.server &
      npx lighthouse http://localhost:3000 --output json --output-path=./lighthouse.json ---chrome-flags="--headless"
      node -p "required('./lighthouse.json').categories.performance.score * 100 + '%'" | xargs -I {} curl \
          --header "Authorization: Token 6f426be8-74f9-4b3c-affb-7c5133000056" \
          --header "Content-Type: application/json" \
          --data "{
            \"value\":\"42 %\",
            \"sha\":\"${CIRCLE_SHA1}\"
          }" \
          https://seriesci.com/api/kelmants/lighthouse-react-seriesci/:series/one
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
